config/routes.rb
Rails.application.routes.draw do
  root to: 'characters#index'

  resources :stories
  resources :characters do
    collection do
      delete :destroy_all
    end
  end
  # map.resources rushing_offenses, :collection => { :destroyall =>
  #                                                      :delete }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/character.rb
class Character < ApplicationRecord
  has_many :rosters, dependent: :delete_all
  has_many :stories, through: :rosters

  def self.search(search)
    if search
      characters = Character.where("name ILIKE ?", "%#{search}%")
      if characters.empty?
        character_data = Marvel::Service.instance.characters({name: 'Spectrum'})
        stories_data = Marvel::Service.instance.character_stories(character_data)
        Marvel::Service.instance.stories_characters(stories_data)
      end
    end
    Character.all.order(:id)
  end

  def self.api(options = {})
    Marvel::Service
  end

  def self.reset_for_new_search
    Roster.delete_all
    Character.delete_all
    Story.delete_all
  end
end

app/models/roster.rb
class Roster < ApplicationRecord
  belongs_to :story
  belongs_to :character
end

app/models/story.rb
class Story < ApplicationRecord
  has_one :roster, dependent: :delete
  has_many :characters, through: :roster
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_action :set_character, only: %i[ show edit update destroy ]

  # GET /characters or /characters.json
  def index
    begin
      if params[:search]
        @characters = Character.search(params[:search])
        @search_message = "All the characters #{params[:search]} worked with:" unless @characters.empty?
      elsif params[:story_marvel_uuid]
        @characters = Story.find_by(marvel_uuid: params[:story_marvel_uuid]).characters
      else
        @characters = Character.all.order(:id)
      end
    rescue StandardError => e
      redirect_to characters_path, notice: "Error: #{e.message}"
    end
  end

  # GET /characters/1 or /characters/1.json
  def show
  end

  # GET /characters/new
  def new
    @character = Character.new
  end

  # GET /characters/1/edit
  def edit
  end

  # POST /characters or /characters.json
  def create
    @character = Character.new(character_params)

    respond_to do |format|
      if @character.save
        format.html { redirect_to @character, notice: "Character was successfully created." }
        format.json { render :show, status: :created, location: @character }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /characters/1 or /characters/1.json
  def update
    respond_to do |format|
      if @character.update(character_params)
        format.html { redirect_to @character, notice: "Character was successfully updated." }
        format.json { render :show, status: :ok, location: @character }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /characters/1 or /characters/1.json
  def destroy
    @character.destroy
    respond_to do |format|
      format.html { redirect_to characters_url, notice: "Character was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def destroy_all
    Character.reset_for_new_search
    respond_to do |format|
      format.html { redirect_to characters_url, notice: "All characters and stories were successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_character
      @character = Character.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def character_params
      params.require(:character).permit(:name, :marvel_uuid, :description, :picture_url)
    end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :set_story, only: %i[ show edit update destroy ]

  # GET /stories or /stories.json
  def index
    if params[:marvel_uuid]
      character = Character.find_by(marvel_uuid: params[:marvel_uuid])
      @stories = character.stories
    else
      @stories = Story.all
    end
  end

  # GET /stories/1 or /stories/1.json
  def show
  end

  # GET /stories/new
  def new
    @story = Story.new
  end

  # GET /stories/1/edit
  def edit
  end

  # POST /stories or /stories.json
  def create
    @story = Story.new(story_params)

    respond_to do |format|
      if @story.save
        format.html { redirect_to @story, notice: "Story was successfully created." }
        format.json { render :show, status: :created, location: @story }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stories/1 or /stories/1.json
  def update
    respond_to do |format|
      if @story.update(story_params)
        format.html { redirect_to @story, notice: "Story was successfully updated." }
        format.json { render :show, status: :ok, location: @story }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stories/1 or /stories/1.json
  def destroy
    @story.destroy
    respond_to do |format|
      format.html { redirect_to stories_url, notice: "Story was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_story
      @story = Story.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def story_params
      params.require(:story).permit(:title, :marvel_uuid, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/characters/_form.html.erb
<%= form_with(model: character) do |form| %>
  <% if character.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(character.errors.count, "error") %> prohibited this character from being saved:</h2>

      <ul>
        <% character.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :marvel_uuid %>
    <%= form.text_field :marvel_uuid %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :picture_url %>
    <%= form.text_field :picture_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/characters/edit.html.erb
<h1>Editing Character</h1>

<%= render 'form', character: @character %>

<%= link_to 'Show', @character %> |
<%= link_to 'Back', characters_path %>

app/views/characters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Search characters</h1>
<p>
  <%= form_tag(characters_path, method: 'get') do %>
    <%= text_field_tag(:search, params[:search]) %>
    <%= submit_tag("Search", name: nil) %>
  <% end %>
  <span>This will load and display all the characters the Marvel superhero worked with. (THIS MAY TAKE UP TO A MINUTE)</span>
</p>
<p>
  <%#= link_to 'Destroy All', :action => 'destroy_all', :confirm => 'Are you sure?', :method => :delete %>
  <%= link_to "Destroy All", destroy_all_characters_path, confirm: "Are you sure?", method: :delete %>
</p>

<br/>
<br/>
<br/>
<br/>
<br/>

<% if @search_message %>
  <p><%= @search_message %></p>
<% end %>

<% if params[:story_marvel_uuid] %>
  <h3><%= "Characters for story #{params[:story_marvel_uuid]}" %></h3>
<% else %>
  <h3>Characters</h3>
<% end %>

<table>
  <thead>
    <tr>
      <th>Picture</th>
      <th>Name</th>
      <th>Marvel id</th>
      <th>Description</th>
      <th colspan="3"></th>
      <th>Stories</th>
    </tr>
  </thead>

  <tbody>
    <% @characters.each do |character| %>
      <tr>
        <td><%= image_tag character.picture_url, style: 'height:100%;width:auto;' %></td>
        <td><%= character.name %></td>
        <td><%= character.marvel_uuid %></td>
        <td><%= character.description %></td>
        <td><%= link_to 'Show', character %></td>
        <td><%#= link_to 'Edit', edit_character_path(character) %></td>
        <td><%#= link_to 'Destroy', character, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Stories', stories_path(marvel_uuid: character.marvel_uuid) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/characters/new.html.erb
<h1>New Character</h1>

<%= render 'form', character: @character %>

<%= link_to 'Back', characters_path %>

app/views/characters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Marvel id:</strong>
  <%= @character.marvel_uuid %>
</p>

<p>
  <strong>Picture:</strong>
  <%= image_tag @character.picture_url %>
</p>

<p>
  <strong>Name:</strong>
  <%= @character.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @character.description %>
</p>


<%= link_to 'Edit', edit_character_path(@character) %> |
<%= link_to 'Back', characters_path %>

app/views/layouts/_header.html.erb
<div>
  <h2><%= link_to "characters", characters_path %></h2>
  <h2><%= link_to "stories", stories_path %></h2>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bvmarvel</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'layouts/header' %>
    <%= yield %>
  </body>
</html>

app/views/stories/_form.html.erb
<%= form_with(model: story) do |form| %>
  <% if story.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(story.errors.count, "error") %> prohibited this story from being saved:</h2>

      <ul>
        <% story.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :marvel_uuid %>
    <%= form.text_field :marvel_uuid %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/stories/edit.html.erb
<h1>Editing Story</h1>

<%= render 'form', story: @story %>

<%= link_to 'Show', @story %> |
<%= link_to 'Back', stories_path %>

app/views/stories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Stories</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Marvel uuid</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stories.each do |story| %>
      <tr>
        <td><%= story.title %></td>
        <td><%= story.marvel_uuid %></td>
        <td><%= story.description %></td>
        <td><%= link_to 'Show', story %></td>
        <td><%#= link_to 'Edit', edit_story_path(story) %></td>
        <td><%#= link_to 'Destroy', story, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Story', new_story_path %>

app/views/stories/new.html.erb
<h1>New Story</h1>

<%= render 'form', story: @story %>

<%= link_to 'Back', stories_path %>

app/views/stories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @story.title %>
</p>

<p>
  <strong>Marvel uuid:</strong>
  <%= @story.marvel_uuid %>
</p>

<p>
  <strong>Description:</strong>
  <%= @story.description %>
</p>

<p>
  <strong>Characters:</strong>
  <%= link_to 'Characters for this story', characters_path(story_marvel_uuid: @story.marvel_uuid) %>

</p>

<%= link_to 'Edit', edit_story_path(@story) %> |
<%= link_to 'Back', stories_path %>